<?php
/**
 * Template Name: Home page webvision
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

	<div id="content-full" class="content-area woocommerce">
		<div class="col-md-8">
			<div id="slide-show-home">
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				  </ol>

				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
					<div class="item active">
					  <img src="wp-content/uploads/2015/12/quang-cao-sac-pin-tet-2016.png" alt="May do Nitrat soeks trong thuc pham">
					  <div class="carousel-caption">
						...
					  </div>
					</div>
					<div class="item">
					  <img src="wp-content/uploads/2015/12/khuyenmai_tet2016.png" alt="May do Nitrat soeks Nuc 019">
					  <div class="carousel-caption">
						...
					  </div>
					</div>
					<div class="item">
					  <img src="wp-content/uploads/2015/12/khuyenmai_2.png" alt="May do an toan thuc pham soeks">
					  <div class="carousel-caption">
					  </div>
					</div>					
				  </div>

				  <!-- Controls -->
				  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				  </a>
				</div>
			</div>
		</div>
		<div class="col-md-4" id="khuyen-mai">
			<a href="#"><img  src="wp-content/uploads/2015/12/may-nitrat_khuyenmai.png" alt="Giao hàng nhanh" /></a>
			<a href="#"><img  src="wp-content/uploads/2015/12/giao-hang-nhanh.png" alt="Dang ky mua may do du luong nitrat" /></a>
		</div>	
		<div class="col-md-12">
			<div id="sp-moi-nhat">
				<h2>Sản phẩm Soeks</h2>
				<?php
				$args = array( 'post_type' => 'product', 'stock' => 1, 'posts_per_page' => 8, 'orderby' =>'date','order' => 'DESC' );		  
				$loop = new WP_Query( $args );	
				echo "<ul class='products'>";
				while ( $loop->have_posts() ) : $loop->the_post();
					//list_produc_single();
					wc_get_template_part( 'content', 'product' );
				endwhile;
				echo "</ul>";
				wp_reset_query();
				?>
			</div>
		</div>

	</div><!-- #content-full -->

<?php get_footer(); ?>
