<?php
/**
 * Template Name: Quản lý IMEI
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
/* function */

include_once('class-imei-camera.php');

if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); 

?>

	<div id="content-full" class="content-area">
	<div id="manager-imei">
		<?php
		if (is_user_logged_in())
		{
			global $current_user;
			get_currentuserinfo();
			if (!$current_user->caps['administrator']) 
			{
				echo "Bạn không có quyền xem trang này"; die;
			}
			
		}
		else {
			echo "Bạn chưa đăng nhập!"; die;
		}
		if (isset($_GET['type']))
		{
			$New_IM = new IM_Camera;
			if ($_GET['type']=="add") 
			{
				if(isset($_GET['IM'])) $New_IM->IMEI = $_GET['IM']; else $error[] = "IM rỗng";
				if(isset($_GET['Name'])) $New_IM->Name = $_GET['Name'];
				$New_IM->Date_in = current_time( 'Y-m-d', $gmt = 0 );
				if(isset($_GET['Date_out'])) $New_IM->Date_out = $_GET['Date_out']; else $error[] = "Date Out rỗng"; 
				if(isset($_GET['Note'])) $New_IM->Note = $_GET['Note'];
				//var_dump($New_IM);
				if($error)
				{
					show_error($error);
				}
				else
				{
					$check = check_imei($New_IM->IMEI);
					if ($check == true)
					{
						$error[] = "IMEI <b>".$New_IM->IMEI."</b> đã tồn tại";
					}
					else{
						$rq = $New_IM->insert();
						$success[] = "Thêm thành công IMEI: <b>".$New_IM->IMEI."</b>";
						

					}
				}

				template_from_add_imei();
			}
			else if ($_GET['type']=="edit") 
			{ 
				if (isset($_GET['o_IMEI'])) $o_IM = $_GET['o_IMEI'];
				if (isset($_GET['IM']))  if ($_GET['IM'] != $_GET['o_IMEI'] ) if (check_imei($_GET['IM'])) $error[]="IMEI <strong>".$_GET['IM']."</strong> đã tồn tại"; else  $came['IMEI'] = $_GET['IM']; else $came['IMEI'] = $_GET['IM']; 
				if (isset($_GET['Date'])) $came['Date_out'] = $_GET['Date'];
				if (isset($_GET['Name'])) $came['Name'] = $_GET['Name'];
				if (isset($_GET['Note'])) $came['Note'] = $_GET['Note'];
				if (!$error) 
				{
					edit_imei($came,$o_IM);
					$success[] = "Sửa thành công!";
					template_from_add_imei();
				}	
				
			}
			else if ($_GET['type']=="del") 
			{
				template_from_add_imei();
				if (isset($_GET['IM'])) 
				{
					$r = delete_imei($_GET['IM']);
					if ($r==0) $error[] = "Xóa IMEI không thành công! IMEI=<strong> ".$_GET['IM']."</strong> không có trong hệ thống!";
					else $success[] = "Xóa thành công IMEI = <strong>".$_GET['IM']."</strong>";
				}
				
			}
		}
		else 
		{
			if (isset($_GET['IM_edit'])) template_from_edit_imei($_GET['IM_edit']);
			else template_from_add_imei();
		}
		
		
		
		
		?>
		
		<div class="col-sm-12">
		<?php 
			if (isset($success)) show_success($success);
			if (isset($error)) if ($error != "")show_error($error);
		?>
		</div>
		<div class="col-sm-12">
			<?php tp_form_search_imei() ?>
		</div><br>
		<h2>Danh sách IMEI</h2>
		<table class="table table-bordered table-hover">
			<tr>
				<th>STT</th>
				<th>IMEI</th>
				<th>Name</th>
				<th>Ngày nhập</th>
				<th>Hạn bảo hành</th>
				<th>Ghi chú</th>
				<th>Thao tác</th>
			</tr>
			<?php 
			template_show_imei();
			?>
			
		</table>
		
	</div>
	</div><!-- #content-full -->

<?php get_footer(); ?>
