<?php
/**
 * Template Name: Check IMEI
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */
 include_once('class-imei-camera.php');

if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); 

?>

	<div id="content-full" class="content-area">
		<div class="col-md-12">
			<label>Kiểm tra sản phẩm</label>
			<aside> Vui lòng nhập Serial hoặc mã IMEI để kiểm tra sản phẩm chính hãng hoặc thời gian bảo hành của sản phẩm tại "Camera giám sát không dây, Camera quan sát chính hãng iCam8"</aside>
			<br>
			<form class="form-inline" method="get" action="/kiem-tra-san-pham/">
				<div class="form-group">
				<input id="code" class="form-control" type="text" name="IMEI" placeholder="Nhập serial hoặc IMEI" value="<?php if (isset($_GET['IMEI'])) echo $_GET['IMEI']; ?>">
				</div>
				<button class="btn btn-danger" type="submit">Kiểm tra</button>
			</form>
		</div>
		<br>
		<div class="col-md-12">
		<br>
			<?php 
				if (isset($_GET['IMEI'])){
					$imei = $_GET['IMEI'];
					$came = get_Camera_by_IMEI($imei);
					if($came)
					{
						foreach ( $came as $item ) 
						{
							$success[] = "<h4><span class='glyphicon glyphicon-ok'></span> Đây là sản phẩm của iCam8</h4><br> Số IMEI: <strong>".$item->IMEI."</strong> <br /> Tên sản phẩm: <strong>".$item->Name."</strong> <br> <span class='glyphicon glyphicon-calendar'></span> Hạn bảo hành: <strong>".$item->Date_out."</strong>";
						}
					}
					else $error[]= "IMEI: <strong>".$imei."</strong> không phải là sản phẩm của iCam8!";
				}
				if (isset($success)) show_success($success);
				if (isset($error)) show_error($error);
			?>
		</div>
		
	</div><!-- #content-full -->

<?php get_footer(); ?>
