<?php
/**
 * Footer Template
 *
 * The template for displaying the footer
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>

<?php responsive_mobile_wrapper_bottom(); // after wrapper content hook ?>
</div><!-- end of #wrapper -->
<?php responsive_mobile_wrapper_end(); // after wrapper hook ?>
</div><!-- end of #container -->
<?php responsive_mobile_container_bottom();?>

<footer id="footer" class="site-footer" role="contentinfo" itemscope="itemscope" itemtype="http://schema.org/WPFooter">
	<?php responsive_mobile_footer_top(); ?>
	<div id="footer-wrapper">

		<div id="footer-widgets-container">
			<?php //get_sidebar( 'footer' ); ?>
			<div id="hau-mai" class="col-md-4">
				<h3><span style="font-size:17px" class="glyphicon glyphicon-wrench"></span> Chính sách</h3>
				<ul>
					<li><a href="#">Chính Sách & quy định chung</a></li>
					<li><a href="#">Hỏi đáp về máy đo Nitrat</a></li>
					<li><a href="#">Nitrat là gì?</a></li>
				</ul>
			</div>
			<div id="chung-toi" class="col-md-4">
				<h3><span style="font-size:17px" class="glyphicon glyphicon-user"></span> Về chúng tôi</h3>
				<ul>
					<li><a href="#">Giới thiệu</a></li>
					<li><a href="#">Cảnh báo hàng giả - hàng nhái - hàng kem chất lượng</a></li>
					<li><a href="#">Tuyển dụng</a></li>
					<li><a href="#">Hệ thông phân phối</a></li>
				</ul>
			</div>
			<div id="chat-luong" class="col-md-4">
				<h3><span style="font-size:17px" class="glyphicon glyphicon-thumbs-up"></span> Face book</h3>
				<div class="fb-page" data-href="https://www.facebook.com/MayDoAnToanThucPhamSoeksVN/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"></div>
			</div>
		</div><!-- #footer-widgets-container-->
		<hr>
		<div class="row-fluid clearfix">
			<div id="thong-tin" class="col-md-6">
				<h4>MAYDONITRAT.VN - Đại lý chính thức tại Việt Nam</h4>
				<div class="col-md-12">
					<p><span style="font-size:16px" class="glyphicon glyphicon-map-marker"></span> Tòa nhà Vinahud, Trung Yên 9, Cầu Giấy, Hà Nội </p>
					<p><span style="font-size:16px" class="glyphicon glyphicon-phone"></span> 096 36 37 999 | 04 22 66 44 88</p>
					<p><span style="font-size:16px" class="glyphicon glyphicon-envelope"> </span><a href="mailto:maydonitrat@gmail.com"> maydonitrat@gmail.com</a></p>
				</div>
			</div>
		</div>
		<div id=’ads-left’>
		
		<?php get_sidebar( 'colophon' ); ?>

		
	</div><!-- #footer-wrapper -->
	<?php responsive_mobile_footer_bottom(); ?>
</footer><!-- #footer -->
<?php responsive_mobile_footer_after(); ?>
<?php responsive_mobile_body_bottom(); ?>
<?php wp_footer(); ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.4&appId=829347377076544";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- Banner chạy dọc -->
<div id="divAdRight" style="display: block; position: fixed; top: 80px;">
<a href="#"><img width="100" src="wp-content/uploads/2015/12/anh-gif-1.gif" width="120" /></a>
</div>
<div id="divAdLeft" style="display: block; position: fixed; top: 80px;">
<a href="#"><img width="100" src="wp-content/uploads/2015/12/anh-gif-2.gif" width="120" /></a>
</div>
<script>
    function FloatTopDiv()
    {
        startLX = ((document.body.clientWidth -MainContentW)/2)-LeftBannerW-LeftAdjust , startLY = TopAdjust+80;
        startRX = ((document.body.clientWidth -MainContentW)/2)+MainContentW+RightAdjust , startRY = TopAdjust+80;
        var d = document;
        function ml(id)
        {
            var el=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id];
            el.sP=function(x,y){this.style.left=x + 'px';this.style.top=y + 'px';};
            el.x = startRX;
            el.y = startRY;
            return el;
        }
        function m2(id)
        {
            var e2=d.getElementById?d.getElementById(id):d.all?d.all[id]:d.layers[id];
            e2.sP=function(x,y){this.style.left=x + 'px';this.style.top=y + 'px';};
            e2.x = startLX;
            e2.y = startLY;
            return e2;
        }
        window.stayTopLeft=function()
        {
            if (document.documentElement && document.documentElement.scrollTop)
                var pY =  document.documentElement;
            else if (document.body)
                var pY =  document.body;
            if (document.body.scrollTop > 30){startLY = 3;startRY = 3;} else {startLY = TopAdjust;startRY = TopAdjust;};
            ftlObj.y += (pY+startRY-ftlObj.y)/16;
            ftlObj.sP(ftlObj.x, ftlObj.y);
            ftlObj2.y += (pY+startLY-ftlObj2.y)/16;
            ftlObj2.sP(ftlObj2.x, ftlObj2.y);
            setTimeout("stayTopLeft()", 1);
        }
        ftlObj = ml("divAdRight");
        //stayTopLeft();
        ftlObj2 = m2("divAdLeft");
        stayTopLeft();
    }
    function ShowAdDiv()
    {
        var objAdDivRight = document.getElementById("divAdRight");
        var objAdDivLeft = document.getElementById("divAdLeft");
        if (document.body.clientWidth < 1000)
        {
            objAdDivRight.style.display = "none";
            objAdDivLeft.style.display = "none";
        }
        else
        {
            objAdDivRight.style.display = "block";
            objAdDivLeft.style.display = "block";
            FloatTopDiv();
        }
    }
</script>
<script>
document.write("<script type='text/javascript' language='javascript'>MainContentW = 1050;LeftBannerW = 120;RightBannerW = 120;LeftAdjust = 5;RightAdjust = 5;TopAdjust = 100;ShowAdDiv();window.onresize=ShowAdDiv;;<\/script>");
</script>
</body>
</html>
